title: "Timothy B. Gravelle"
description: "Academic profile page"
author:
  name: "Timothy B. Gravelle"
  email: "tgravelle@wlu.ca"
theme: minima
baseurl: "" 
url: "https://tgravelle.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
header_pages:
  - index.md
  - bio.md
