title: "Timothy B. Gravelle"
description: "Academic profile page"
author:
  name: "Timothy B. Gravelle"
  email: "tgravelle@wlu.ca"

# Use a supported theme
theme: minima

# Hide automatic page titles
show_title: false

# Site URLs
baseurl: "" 
url: "https://tgravelle.github.io"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
