title: "Timothy B. Gravelle"

description: "Academic profile page"
author:
  name: "Timothy B. Gravelle"
  email: "tgravelle@wlu.ca"

theme: minima
show_title: false
baseurl: ""
url: "https://tgravelle.github.io"

markdown: kramdown
plugins:
  - jekyll-feed

navigation:
  - title: "Home"
    url: "/"
  - title: "Bio"
    url: "/bio"
  - title: "CV"
    url: "/assets/CV-Tim Gravelle.pdf"
