title: "Timothy B. Gravelle"
description: "Academic profile page"
theme: minima
author:
  name: "Timothy B. Gravelle"
  email: "tgravelle@wlu.ca"
  
baseurl: "" #
url: "https://tgravelle.github.io"

show_title: false

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
